---
# tasks file for create_vm
- name: select server type
  include_vars: "{{ server_type }}.yml"
- name: create instance
  os_server:
    state: present
    name: "{{ item.vm_name }}"
    image: "{{ vm_image }}"
    key_name: "{{ vm_key_name }}"
    timeout: 60
    flavor: "{{ vm_flavor }}"
    network: "{{ vm_network }}"
    auto_ip: yes
    security_groups: "{{ vm_security_groups }}"
    meta: "{{ vm_meta  }}" 
  with_items: "{{ names }}"
  register: "{{ vm_register }}"
