---
# tasks file for create_sec_grp_rule
- name: create security group rule
  os_security_group_rule:
    security_group: "{{ sg_rule }}"
    protocol: "{{ rule_protocol }}"
    port_range_min: "{{ rule_port_range_min }}"
    port_range_max: "{{ rule_port_range_max }}"
    remote_ip_prefix: 0.0.0.0/0
